[package]
name = "ball_in_a_box"
version = "0.1.0"
edition = "2021"

[dependencies]
macroquad = "0.4.13"
nanoserde = "0.1.37"

[patch.crates-io]
miniquad = {git = "https://github.com/InZan17/miniquad/", branch = "screen-mouse-position"}
